### ISSUE TITLE
Use list for authors in YAML header

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#118]
* Current: `author: Andy Shu, Chao Tianyi`
* Better: 

```
author: 
- Andy Shu
- Chao Tianyi
```

This is easier for later stats & analysis. 

Even better: (more attractive for community authors)

```
author: 
- name: Andy Shu
  url: http://xxxx
- name: Chao Tianyi
  url: http://yyyyy
```

Ref PR: 
https://github.com/initiumlab/initiumlab.com/pull/115/files
